import { ComponentDoc } from '../models/component-doc.model';

export const COMPONENT_REGISTRY: ComponentDoc[] = [
  {
    id: 'input',
    name: 'Reusable Input',
    category: 'form-controls',
    description:
      'A highly configurable input component supporting all HTML input types, validation, prefix/suffix, hints, and reactive forms integration.',
    icon: 'text_fields',
    route: '/components/input',
    tags: ['input', 'text', 'form', 'validation', 'reactive'],
    isNew: false,
    features: [
      'All standard input types',
      'Reactive Forms & ControlValueAccessor',
      'Auto validation messages',
      'Prefix & Suffix icons',
      'Character counter',
      'Hint text',
      'Multiple appearances',
    ],
    inputs: [
      { name: 'label', type: 'string', description: 'Field label text' },
      { name: 'placeholder', type: 'string', description: 'Placeholder text' },
      { name: 'type', type: 'InputType', default: 'text', description: 'HTML input type' },
      { name: 'appearance', type: 'fill | outline', default: 'outline', description: 'Material appearance' },
      { name: 'required', type: 'boolean', default: 'false', description: 'Whether field is required' },
      { name: 'disabled', type: 'boolean', default: 'false', description: 'Whether field is disabled' },
      { name: 'readonly', type: 'boolean', default: 'false', description: 'Whether field is readonly' },
      { name: 'hint', type: 'string', description: 'Hint text below field' },
      { name: 'prefixIcon', type: 'string', description: 'Material icon for prefix' },
      { name: 'suffixIcon', type: 'string', description: 'Material icon for suffix' },
      { name: 'maxLength', type: 'number', description: 'Maximum character length' },
      { name: 'control', type: 'FormControl', required: true, description: 'Reactive form control' },
    ],
  },
  {
    id: 'select',
    name: 'Reusable Select',
    category: 'form-controls',
    description:
      'A powerful select component supporting single/multiple selection, search, select-all, clear, loading, and empty states.',
    icon: 'arrow_drop_down_circle',
    route: '/components/select',
    tags: ['select', 'dropdown', 'multi', 'search', 'form'],
    features: [
      'Single & multiple selection',
      'Built-in search filter',
      'Select all / Clear all',
      'Loading & empty states',
      'Custom display & value keys',
      'ControlValueAccessor',
    ],
  },
  {
    id: 'autocomplete',
    name: 'Reusable Autocomplete',
    category: 'form-controls',
    description:
      'Autocomplete with debouncing, async data support, loading indicator, and no-results state.',
    icon: 'search',
    route: '/components/autocomplete',
    tags: ['autocomplete', 'search', 'async', 'typeahead'],
    features: [
      'Debounced search',
      'Async API support',
      'Loading indicator',
      'No results state',
      'Clear button',
      'Custom display',
    ],
  },
  {
    id: 'table',
    name: 'Reusable Table',
    category: 'data',
    description:
      'Full-featured data table with dynamic columns, sorting, pagination, search, selection, row actions, and server-side support.',
    icon: 'table_chart',
    route: '/components/table',
    tags: ['table', 'data', 'grid', 'pagination', 'sort', 'filter'],
    isNew: true,
    features: [
      'Dynamic column configuration',
      'Client & server-side sorting',
      'Pagination with page size',
      'Global search',
      'Row selection (single & multiple)',
      'Row actions (view, edit, delete)',
      'Column visibility toggle',
      'Loading & empty states',
      'Sticky header & columns',
      'Expandable rows',
    ],
  },
  {
    id: 'dialog',
    name: 'Dialog Service',
    category: 'surface',
    description:
      'Reusable dialog service for opening dynamic component dialogs with data passing and result handling.',
    icon: 'open_in_full',
    route: '/components/dialog',
    tags: ['dialog', 'modal', 'overlay', 'service'],
    isNew: true,
    features: [
      'Dynamic component injection',
      'Data passing',
      'Result handling',
      'Confirm dialog',
      'Configurable size',
      'Backdrop control',
    ],
  },
];
